#!/usr/bin/env bash
set -euo pipefail

PROJECT_NAME="zhongzhou-smart-care"
EXPORT_DIR="${EXPORT_DIR:-/root/${PROJECT_NAME}}"
DATE_STR="$(date +%Y%m%d)"

TOMCAT_DIR="/opt/apache-tomcat-9.0.100"
NGINX_CONF_DIR="/etc/nginx"
NGINX_HTML_DIR="/var/www/dist"

NODE2_HOST="192.168.88.102"
NODE3_HOST="192.168.88.103"

SSH_OPTS=(-o BatchMode=yes -o StrictHostKeyChecking=accept-new)

GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

log() {
  echo -e "${BLUE}$*${NC}"
}

step() {
  echo -e "\n${GREEN}$*${NC}"
}

warn() {
  echo -e "${RED}$*${NC}"
}

log "🚀 开始执行中州养老项目资产收集任务..."
log "📂 目标仓库目录: ${EXPORT_DIR}"

mkdir -p "${EXPORT_DIR}"/{scripts,conf,sql,logs_sample,docs,ansible}
mkdir -p "${EXPORT_DIR}/conf"/{node1_mysql,node1_redis,node1_nginx,node2_tomcat,node3_nginx}

step "--> [Node1] 正在收集本地配置..."

echo "正在搜索并复制 Shell 脚本..."
find /root -maxdepth 2 -name "*.sh" -not -name "collect_zhongzhou.sh" -exec cp {} "${EXPORT_DIR}/scripts/" \; 2>/dev/null || true
if [ -d "/export/shell" ]; then
  cp -r /export/shell/* "${EXPORT_DIR}/scripts/" 2>/dev/null || true
fi

crontab -l > "${EXPORT_DIR}/conf/node1_crontab.txt" 2>/dev/null || true

echo "收集 Node1 Nginx 配置..."
if [ -d "${NGINX_CONF_DIR}" ]; then
  cp "${NGINX_CONF_DIR}/nginx.conf" "${EXPORT_DIR}/conf/node1_nginx/" 2>/dev/null || true
  cp -r "${NGINX_CONF_DIR}/conf.d" "${EXPORT_DIR}/conf/node1_nginx/" 2>/dev/null || true
fi

if [ -f "/etc/my.cnf" ]; then
  cp /etc/my.cnf "${EXPORT_DIR}/conf/node1_mysql/" 2>/dev/null || true
fi

step "--> MySQL Schema (仅结构)"
if command -v mysqldump &> /dev/null; then
  if [ -n "${MYSQL_DEFAULTS_FILE:-}" ] && [ -f "${MYSQL_DEFAULTS_FILE}" ]; then
    mysqldump --defaults-extra-file="${MYSQL_DEFAULTS_FILE}" --all-databases --no-data > "${EXPORT_DIR}/sql/db_schema.sql" || true
  elif [ -n "${MYSQL_DUMP_PASSWORD:-}" ]; then
    mysqldump -uroot -p"${MYSQL_DUMP_PASSWORD}" --all-databases --no-data > "${EXPORT_DIR}/sql/db_schema.sql" || true
  else
    warn "⚠️  未提供 MySQL 凭据，跳过 Schema 导出。"
  fi
else
  warn "⚠️  未找到 mysqldump，跳过 Schema 导出。"
fi

if [ -d "/etc/ansible" ]; then
  cp /etc/ansible/ansible.cfg "${EXPORT_DIR}/ansible/" 2>/dev/null || true
  cp /etc/ansible/hosts "${EXPORT_DIR}/ansible/inventory" 2>/dev/null || true
  if [ -d "/root/ansible" ]; then
    cp -r /root/ansible/* "${EXPORT_DIR}/ansible/" 2>/dev/null || true
  fi
fi

step "--> [Node2] 正在远程收集 Tomcat/Java 配置..."
ssh "${SSH_OPTS[@]}" "root@${NODE2_HOST}" "mkdir -p /tmp/collect_node2" || true
scp "root@${NODE2_HOST}:${TOMCAT_DIR}/conf/server.xml" "${EXPORT_DIR}/conf/node2_tomcat/" 2>/dev/null || true
scp "root@${NODE2_HOST}:${TOMCAT_DIR}/conf/context.xml" "${EXPORT_DIR}/conf/node2_tomcat/" 2>/dev/null || true
ssh "${SSH_OPTS[@]}" "root@${NODE2_HOST}" "tail -n 50 ${TOMCAT_DIR}/logs/catalina.out" > "${EXPORT_DIR}/logs_sample/node2_tomcat_sample.log" 2>/dev/null || true

step "--> [Node3] 正在远程收集 Nginx 配置与前端资源目录..."
scp "root@${NODE3_HOST}:${NGINX_CONF_DIR}/nginx.conf" "${EXPORT_DIR}/conf/node3_nginx/" 2>/dev/null || true
scp -r "root@${NODE3_HOST}:${NGINX_CONF_DIR}/conf.d" "${EXPORT_DIR}/conf/node3_nginx/" 2>/dev/null || true
ssh "${SSH_OPTS[@]}" "root@${NODE3_HOST}" "tree -L 2 ${NGINX_HTML_DIR}" > "${EXPORT_DIR}/docs/node3_html_tree.txt" 2>/dev/null || true

step "--> 正在生成项目文档..."
cat > "${EXPORT_DIR}/README.md" <<'DOC'
# 🏥 中州养老 (Zhongzhou Smart Care) - 运维实战项目

> 这是一个基于 CentOS 的分布式微服务架构部署项目收集包。
> 包含 Nginx、Tomcat、MySQL、Redis、Ansible 等核心资产，用于作品集展示与复盘。

## 📂 项目结构

```text
.
├── ansible/        # 自动化部署剧本
├── conf/           # 各节点核心配置文件
├── scripts/        # 运维 Shell 脚本
├── sql/            # 数据库初始化脚本 (Schema)
├── logs_sample/    # 运行日志样本
└── docs/           # 项目文档与架构说明
```

## 🏗️ 架构说明

* **Node1 (Manager/DB)**: MySQL、Redis、Ansible 控制端
* **Node2 (App)**: Tomcat (后端 Java API)
* **Node3 (Web/LB)**: Nginx (前端静态资源 + 反向代理)

---
*Generated by Hai Ting's Ops Collection Script*
DOC

cat > "${EXPORT_DIR}/.gitignore" <<'DOC'
*.log
*.tar.gz
*.zip
.DS_Store
passwords.txt
id_rsa
DOC

log "✅ 收集完成：${EXPORT_DIR}"
log "💡 建议：人工检查 SQL/敏感信息后再上传 GitHub。"

